using CodeIndex.Core;
using CodeIndex.Roslyn;

namespace CodeIndex.Roslyn.Tests;

public class WorkspaceIndexBuildersTests
{
    [Fact]
    public async Task BuildAsync_GeneratesStructuredFileSummaries()
    {
        var solutionPath = GetSolutionPath();
        var builder = new WorkspaceFileIndexBuilder();

        var files = await builder.BuildAsync(solutionPath);
        var programFile = Assert.Single(files, file => file.Path == "src/CodeIndex.Cli/Program.cs");

        Assert.Contains("top-level statements", programFile.Summary, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task BuildAsync_ExtractsWorkspaceInspectorSymbol()
    {
        var solutionPath = GetSolutionPath();
        var fileBuilder = new WorkspaceFileIndexBuilder();
        var symbolBuilder = new WorkspaceSymbolIndexBuilder();

        var files = await fileBuilder.BuildAsync(solutionPath);
        var symbols = await symbolBuilder.BuildAsync(solutionPath, files);

        Assert.Contains(symbols, symbol => symbol.Name == "WorkspaceInspector" && symbol.Kind == "class");
        Assert.Contains(symbols, symbol => symbol.Name == "InspectAsync" && symbol.Kind == "method");
    }

    [Fact]
    public async Task BuildAsync_GeneratesContainsEdgesForIndexedSymbols()
    {
        var solutionPath = GetSolutionPath();
        var builder = new WorkspaceEdgeIndexBuilder();

        var edges = await builder.BuildAsync(solutionPath);

        Assert.Contains(edges, edge =>
            edge.Type == "contains" &&
            edge.From == "s:T:CodeIndex.Roslyn.WorkspaceInspector" &&
            edge.To == "s:M:CodeIndex.Roslyn.WorkspaceInspector.InspectAsync(System.String,System.Threading.CancellationToken)");

        Assert.Equal(edges.OrderBy(edge => edge.Type, StringComparer.Ordinal)
            .ThenBy(edge => edge.From, StringComparer.Ordinal)
            .ThenBy(edge => edge.To, StringComparer.Ordinal), edges);
    }

    [Fact]
    public async Task BuildAsync_IncludeGenerated_AddsObjDocuments()
    {
        var solutionPath = GetSolutionPath();
        var builder = new WorkspaceFileIndexBuilder();

        var files = await builder.BuildAsync(solutionPath, includeGenerated: true);

        Assert.Contains(files, file => file.Path.Contains("/obj/", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task BuildAsync_CurrentSolution_IsDeterministic_AndValidates()
    {
        var solutionPath = GetSolutionPath();
        var fileBuilder = new WorkspaceFileIndexBuilder();
        var symbolBuilder = new WorkspaceSymbolIndexBuilder();
        var edgeBuilder = new WorkspaceEdgeIndexBuilder();

        var firstFiles = await fileBuilder.BuildAsync(solutionPath);
        var firstSymbols = await symbolBuilder.BuildAsync(solutionPath, firstFiles);
        var firstEdges = await edgeBuilder.BuildAsync(solutionPath);

        var secondFiles = await fileBuilder.BuildAsync(solutionPath);
        var secondSymbols = await symbolBuilder.BuildAsync(solutionPath, secondFiles);
        var secondEdges = await edgeBuilder.BuildAsync(solutionPath);

        Assert.Equal(firstFiles, secondFiles);
        Assert.Equal(firstSymbols, secondSymbols);
        Assert.Equal(firstEdges, secondEdges);

        var snapshot = new CodeIndexSnapshot(
            new CodeIndexMeta("1.0", "0.1.0", "code-index", DateTimeOffset.UtcNow, Path.GetDirectoryName(solutionPath)!, solutionPath, "solution"),
            firstFiles,
            firstSymbols,
            firstEdges);

        var validator = new CodeIndexValidator();
        validator.ValidateOrThrow(snapshot);
    }

    [Fact]
    public async Task BuildAsync_FiltersGeneratedSuffixFiles_ByDefault()
    {
        var projectPath = CreateTempProject(
            ("RegularFile.cs", "namespace Sample; public class RegularFile {}"),
            ("GeneratedFile.g.cs", "namespace Sample; public class GeneratedFile {}"),
            ("GeneratedFile.g.i.cs", "namespace Sample; public class GeneratedFileIntermediate {}"),
            ("DesignerFile.designer.cs", "namespace Sample; public class DesignerFile {}"),
            ("Auto.generated.cs", "namespace Sample; public class AutoGeneratedFile {}"));

        try
        {
            var builder = new WorkspaceFileIndexBuilder();

            var filteredFiles = await builder.BuildAsync(projectPath);
            var allFiles = await builder.BuildAsync(projectPath, includeGenerated: true);

            Assert.Contains(filteredFiles, file => file.Path == "RegularFile.cs");
            Assert.DoesNotContain(filteredFiles, file => file.Path == "GeneratedFile.g.cs");
            Assert.DoesNotContain(filteredFiles, file => file.Path == "GeneratedFile.g.i.cs");
            Assert.DoesNotContain(filteredFiles, file => file.Path == "DesignerFile.designer.cs");
            Assert.DoesNotContain(filteredFiles, file => file.Path == "Auto.generated.cs");

            Assert.Contains(allFiles, file => file.Path == "RegularFile.cs");
            Assert.Contains(allFiles, file => file.Path == "GeneratedFile.g.cs");
            Assert.Contains(allFiles, file => file.Path == "GeneratedFile.g.i.cs");
            Assert.Contains(allFiles, file => file.Path == "DesignerFile.designer.cs");
            Assert.Contains(allFiles, file => file.Path == "Auto.generated.cs");
        }
        finally
        {
            var tempDirectory = Path.GetDirectoryName(projectPath);

            if (tempDirectory is not null && Directory.Exists(tempDirectory))
            {
                Directory.Delete(tempDirectory, recursive: true);
            }
        }
    }

    private static string GetSolutionPath()
    {
        return Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../code-index.sln"));
    }

    private static string CreateTempProject(params (string FileName, string Content)[] files)
    {
        var tempDirectory = Path.Combine(Path.GetTempPath(), $"code-index-roslyn-tests-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDirectory);

        var projectPath = Path.Combine(tempDirectory, "Sample.csproj");
        File.WriteAllText(projectPath, """
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
""");

        foreach (var file in files)
        {
            File.WriteAllText(Path.Combine(tempDirectory, file.FileName), file.Content);
        }

        return projectPath;
    }
}